name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source repo
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Login DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Setup Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. Build & push Docker image
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            theopen4/testgitopsimage:latest
            theopen4/testgitopsimage:${{ github.sha }}

      # 5. Update GitOps repo with new image tag
      - name: Update GitOps repository
        env:
          TOKEN: ${{ secrets.GITOPS_PAT }}
        run: |
          git clone https://github.com/theopen4/grade-api-gitops.git
          cd grade-api-gitops
      
          # Modifier l'image dans deployment.yaml
          sed -i "s|image: .*|image: theopen4/testgitopsimage:${{ github.sha }}|g" deployment.yaml
      
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      
          git add deployment.yaml
          git commit -m "Update image to ${{ github.sha }}"
      
          # Push avec authentification en HTTPS
          git push https://theopen4:${TOKEN}@github.com/theopen4/grade-api-gitops.git main
